services:
  postgres:
    container_name: postgres-sql
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: skon
      POSTGRES_DB: db_book_social
      PGDATA: /var/lib/postgresql/data/db_pgdata
    volumes:
      - postgres:/var/lib/postgresql/data/db_pgdata
    ports:
      - "5432:5432"
    networks:
      - spring-project
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev_1
    image: maildev_1/maildev-1
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - spring-project

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
