spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_book_social
    username: postgres
    password: skon
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql

  mail:
    host: localhost
    port: 1025
    username: skon
    password: skon
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

  application:
    security:
      jwt:
        secret-key: KW6YutYp4TZ/6ev5CJpeLXHZU8vZ2m7nOdSCGVnP5bo=
        expiration: 864000
    mailing:
      frontend-url: http://localhost:4200/activate-account
