spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB

server:
  servlet:
    context-path: /api/v1
  port: 8088

springdoc:
  default-produces-media-type: application/json
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui